'use strict';
const menuButton=document.querySelector('.menu-toggle');
const navigation=document.querySelector('#navigation');
function closeMenu(){navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Ouvrir le menu');}
menuButton.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu');});
navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
const profiles={commerce:{tag:'E-COMMERCE',title:'Vous développez la marque.<br>Nous préparons la structure.',description:'Votre boutique grandit et vos clients sont dans plusieurs pays. Construisez une société cohérente avec votre modèle, vos fournisseurs et vos moyens d’encaissement.',items:['Constitution de votre société Hong Kong Ltd.','Préparation de votre dossier bancaire','Documents et suivi réunis dans votre espace'],cta:'Parlons de votre boutique'},trade:{tag:'IMPORT & EXPORT',title:'Vous trouvez les opportunités.<br>Nous cadrons le départ.',description:'Vous échangez avec des fournisseurs en Asie et des acheteurs à l’international. Posez les bases de votre société et préparez vos besoins de paiements professionnels.',items:['Une structure pour organiser vos contrats','Un dossier bancaire qui présente vos flux','Un accompagnement pour les démarches de création'],cta:'Parlons de vos échanges'},services:{tag:'SERVICES & CONSEIL',title:'Votre expertise voyage.<br>Votre entreprise suit.',description:'Consultant, agence ou prestataire : vos clients dépassent les frontières. Étudiez une structure adaptée à votre activité internationale et à votre façon de travailler.',items:['Une création cadrée autour de votre activité','Des documents pour vos échanges professionnels','Un suivi administratif après la constitution'],cta:'Parlons de votre activité'}};
const tabs=[...document.querySelectorAll('[data-profile]')];
function selectProfile(tab){const profile=profiles[tab.dataset.profile];tabs.forEach(item=>{const selected=item===tab;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1;});document.querySelector('#profile-panel').setAttribute('aria-labelledby',tab.id);document.querySelector('#profile-tag').textContent=profile.tag;document.querySelector('#profile-title').innerHTML=profile.title;document.querySelector('#profile-description').textContent=profile.description;document.querySelector('#profile-list').replaceChildren(...profile.items.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));document.querySelector('#profile-cta').replaceChildren(document.createTextNode(profile.cta+' '),Object.assign(document.createElement('span'),{textContent:'↗'}));}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectProfile(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();selectProfile(tabs[next]);tabs[next].focus();}});});
document.querySelectorAll('.china-enquiry').forEach(link=>link.addEventListener('click',()=>{document.querySelector('#project-service').value='china';}));
const projectForm=document.querySelector('#project-form');
projectForm.addEventListener('submit',event=>{event.preventDefault();if(!projectForm.reportValidity())return;const service=projectForm.elements.service;const message=['Bonjour Luminos,',`Nom : ${projectForm.elements.name.value.trim()}`,`E-mail : ${projectForm.elements.email.value.trim()}`,`Projet : ${service.options[service.selectedIndex].text}`, '',projectForm.elements.message.value.trim()].join('\n');const url='https://wa.me/85266455426?text='+encodeURIComponent(message);window.open(url,'_blank','noopener,noreferrer');const status=document.querySelector('#form-status');status.replaceChildren(document.createTextNode('Si WhatsApp ne s’ouvre pas, '));const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='ouvrez votre message ici';status.append(link);});
// Preserve referral attribution and the existing production tracking endpoint.
(function(){try{const ref=new URLSearchParams(window.location.search).get('ref');if(ref){localStorage.setItem('lum_ref',ref);localStorage.setItem('lum_ref_ts',Date.now().toString());fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:ref})}).catch(()=>{});}}catch(e){}})();
