/* Presentation layer. Production authentication and payments stay on luminoscorp.com. */
const copy={
fr:{'hero.badge':'Votre business commence à Hong Kong','hero.title':'Votre société à<br><em>Hong Kong.</em><br>Le monde devant vous.','hero.sub':'Création de société, accompagnement bancaire et suivi annuel. Luminos vous accompagne à chaque étape de votre activité à Hong Kong.','hero.cta1':'Créer ma société','hero.cta2':'Découvrir les étapes','services.title':'Un partenaire. Chaque étape.','services.sub':'De la création au suivi de votre société, retrouvez les services essentiels au même endroit.','pricing.title':'Votre prochaine étape, au bon prix.','new.offer':'Création de votre société','new.stat1':'Création','new.stat1sub':'Société Hong Kong Ltd.','new.stat2':'Banque','new.stat2sub':'Accompagnement dédié','new.stat3':'Suivi','new.stat3sub':'Votre espace client','cf.send':'Continuer sur WhatsApp','new.note':'Votre message sera préparé dans WhatsApp. Vous pourrez le vérifier avant de l’envoyer.','pr1.f5':'Accompagnement à l’ouverture de compte'},
en:{'hero.badge':'Your business starts in Hong Kong','hero.title':'Your company in<br><em>Hong Kong.</em><br>A world of possibility.','hero.sub':'Company formation, banking support and annual maintenance. Luminos supports every step of your business in Hong Kong.','hero.cta1':'Start my company','hero.cta2':'Explore the process','services.title':'One partner. Every step.','services.sub':'From incorporation to ongoing company support, find the essential services in one place.','pricing.title':'Your next step. Clearly priced.','new.offer':'Company formation','new.stat1':'Formation','new.stat1sub':'Hong Kong limited company','new.stat2':'Banking','new.stat2sub':'Dedicated support','new.stat3':'Tracking','new.stat3sub':'Your client dashboard','cf.send':'Continue on WhatsApp','new.note':'Your message will open in WhatsApp. Review it before sending.','pr1.f5':'Bank account application support'},
es:{'hero.badge':'Tu negocio empieza en Hong Kong','hero.title':'Tu empresa en<br><em>Hong Kong.</em><br>El mundo por delante.','hero.sub':'Constitución de empresas, apoyo bancario y mantenimiento anual. Luminos te acompaña en cada etapa de tu negocio en Hong Kong.','hero.cta1':'Crear mi empresa','hero.cta2':'Ver las etapas','services.title':'Un socio. Cada etapa.','new.offer':'Constitución de tu empresa','new.stat1':'Constitución','new.stat1sub':'Sociedad en Hong Kong','new.stat2':'Banca','new.stat2sub':'Apoyo personalizado','new.stat3':'Seguimiento','new.stat3sub':'Tu panel de cliente','cf.send':'Continuar en WhatsApp','new.note':'Revisa tu mensaje en WhatsApp antes de enviarlo.','pr1.f5':'Apoyo en la solicitud bancaria'},
zh:{'hero.badge':'从香港开启您的事业','hero.title':'在<em>香港</em>成立公司，<br>面向世界。','hero.sub':'公司注册、银行开户协助及年度维护。徕米诺陪伴您在香港开展业务的每一步。','hero.cta1':'注册公司','hero.cta2':'了解流程','services.title':'一个伙伴，全程支持','new.offer':'公司注册','new.stat1':'公司注册','new.stat1sub':'香港有限公司','new.stat2':'银行服务','new.stat2sub':'专业协助','new.stat3':'进度跟踪','new.stat3sub':'客户中心','cf.send':'在 WhatsApp 中继续','new.note':'请在 WhatsApp 中确认信息后再发送。','pr1.f5':'银行开户申请协助'}
};
const photosCopy={
fr:{'photos.hero':'Aux côtés de votre business','photos.label':'Dans les coulisses de Luminos','photos.title':'Des visages derrière votre projet.','photos.intro':'Une société, c’est le début d’une histoire. De vos premières questions à la préparation de votre dossier, échangez avec des personnes qui vous accompagnent.','photos.cta':'Parlons de votre projet ↗','photos.caption1':'Bienvenue dans nos bureaux.','photos.caption2':'Votre projet, au cœur du quotidien.','photos.nav':'Luminos'},
en:{'photos.hero':'By your side in business','photos.label':'Behind the scenes at Luminos','photos.title':'The people behind your next chapter.','photos.intro':'A company is the start of a story. From your first questions to preparing your application, speak with the people supporting your project.','photos.cta':'Let’s talk about your project ↗','photos.caption1':'Welcome to our offices.','photos.caption2':'Your project, part of our everyday.','photos.nav':'Luminos'},
es:{'photos.hero':'A tu lado en los negocios','photos.label':'Dentro de Luminos','photos.title':'Las personas detrás de tu proyecto.','photos.intro':'Una empresa es el comienzo de una historia. Desde tus primeras preguntas hasta la preparación de tu expediente, habla con las personas que te acompañan.','photos.cta':'Hablemos de tu proyecto ↗','photos.caption1':'Bienvenido a nuestras oficinas.','photos.caption2':'Tu proyecto, parte de nuestro día a día.','photos.nav':'Luminos'},
zh:{'photos.hero':'陪伴您的事业','photos.label':'走进徕米诺','photos.title':'您项目背后的伙伴。','photos.intro':'一家公司，是一个故事的开始。从最初的咨询到申请资料的准备，我们陪伴您迈出每一步。','photos.cta':'与我们聊聊您的计划 ↗','photos.caption1':'欢迎来到我们的办公室。','photos.caption2':'您的项目，我们的日常。','photos.nav':'徕米诺'}
};
Object.entries(photosCopy).forEach(([key,value])=>Object.assign(copy[key],value));
const destinationsCopy={
fr:{'dest.label':'Hong Kong & Chine','dest.title':'Deux destinations. Votre prochaine étape.','dest.hk.title':'Votre société à Hong Kong','dest.hk.text':'Création de société, accompagnement bancaire et suivi annuel : retrouvez notre offre pour lancer votre activité à Hong Kong.','dest.hk.cta':'Découvrir l’offre Hong Kong','dest.cn.name':'Chine','dest.cn.title':'Votre société en Chine','dest.cn.text':'Vous souhaitez développer votre activité en Chine ? Luminos vous accompagne dans votre projet de création de société. Échangeons sur votre activité et la ville envisagée.','dest.cn.cta':'Demander un devis pour la Chine','cf.china':'Création de société en Chine — sur devis'},
en:{'dest.label':'Hong Kong & China','dest.title':'Two destinations. Your next chapter.','dest.hk.title':'Your company in Hong Kong','dest.hk.text':'Company formation, banking support and annual maintenance: explore our offer to start your business in Hong Kong.','dest.hk.cta':'Explore the Hong Kong offer','dest.cn.name':'China','dest.cn.title':'Your company in China','dest.cn.text':'Looking to grow your business in China? Luminos supports your company formation project. Let’s discuss your business and preferred city.','dest.cn.cta':'Request a quote for China','cf.china':'Company formation in China — request a quote'},
es:{'dest.label':'Hong Kong y China','dest.title':'Dos destinos. Tu próximo paso.','dest.hk.title':'Tu empresa en Hong Kong','dest.hk.text':'Constitución de empresas, apoyo bancario y mantenimiento anual: descubre nuestra oferta para empezar en Hong Kong.','dest.hk.cta':'Ver la oferta de Hong Kong','dest.cn.name':'China','dest.cn.title':'Tu empresa en China','dest.cn.text':'¿Quieres desarrollar tu actividad en China? Luminos te acompaña en tu proyecto de constitución. Hablemos de tu actividad y de la ciudad elegida.','dest.cn.cta':'Pedir presupuesto para China','cf.china':'Constitución en China — presupuesto personalizado'},
zh:{'dest.label':'香港及中国内地','dest.title':'两地选择，开启新篇章。','dest.hk.title':'在香港成立公司','dest.hk.text':'公司注册、银行开户协助及年度维护：了解我们的香港公司注册服务。','dest.hk.cta':'了解香港服务','dest.cn.name':'中国内地','dest.cn.title':'在中国内地成立公司','dest.cn.text':'希望在中国内地开展业务？徕米诺协助您的公司注册计划。欢迎与我们沟通业务及意向城市。','dest.cn.cta':'咨询中国内地注册报价','cf.china':'中国内地公司注册 — 咨询报价'}
};
Object.entries(destinationsCopy).forEach(([key,value])=>Object.assign(copy[key],value));
Object.entries(copy).forEach(([key,value])=>Object.assign(T[key],value));
const form=document.querySelector('.contact-form');
const note=document.createElement('p');note.className='form-note';note.dataset.i18n='new.note';form.append(note);
form.querySelectorAll('input,select,textarea').forEach((el,i)=>{el.id='contact-field-'+i;const label=el.closest('.form-group')?.querySelector('label');if(label)label.htmlFor=el.id;});
form.querySelector('input[type="email"]').required=true;
form.querySelector('textarea').required=true;
function contactWhatsApp(){
 const fields=[...form.querySelectorAll('input,select,textarea')];
 for(const field of fields)if(!field.reportValidity())return;
 const [first,last,email,service,message]=fields.map(el=>el.value.trim());
 const text=`${first} ${last}\n${email}\n${service}\n\n${message}`;
 window.open('https://wa.me/85266455426?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');
}
const menu=document.querySelector('.menu-toggle');
menu.addEventListener('click',()=>{const open=document.querySelector('.nav-center').classList.toggle('is-open');menu.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.nav-center a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.nav-center').classList.remove('is-open');menu.setAttribute('aria-expanded','false');}));
document.querySelectorAll('.faq-q').forEach((q,i)=>{
 q.setAttribute('role','button');q.tabIndex=0;q.setAttribute('aria-expanded','false');
 const answer=q.nextElementSibling;if(answer){answer.id='faq-answer-'+i;q.setAttribute('aria-controls',answer.id);}
 q.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();q.click();}});
 q.addEventListener('click',()=>document.querySelectorAll('.faq-q').forEach(item=>item.setAttribute('aria-expanded',String(item.parentElement.classList.contains('open')))));
});
setLang(localStorage.getItem('lum_lang')||'fr');

document.querySelectorAll('.china-enquiry').forEach(link=>link.addEventListener('click',()=>{const select=document.querySelector('.contact-form select');select.value='china';select.dispatchEvent(new Event('change',{bubbles:true}));}));
